import { THREAT_COLORS, THREAT_LABEL } from '../../constants/threat'

export { THREAT_COLORS, THREAT_LABEL }

export const AUDIO_ATTACK_REGISTRY = {
  transcription: {
    id: 'transcription',
    name: 'Targeted Transcription',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Targeted',
    threat: 'whitebox',
    year: 2018,
    norm: 'L∞',
    authors: 'Carlini & Wagner',
    desc: 'Force ASR to output an attacker-chosen transcript. C&W optimisation (Adam) or PGD sign-based. Modifies audio so Whisper outputs exact target text.',
    params: ['audio', 'asr_model', 'target_text', 'epsilon', 'iterations', 'lr', 'optimizer'],
  },
  hidden: {
    id: 'hidden',
    name: 'Hidden Command',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Targeted',
    threat: 'whitebox',
    year: 2018,
    norm: 'L∞',
    authors: 'Yuan et al. (CommanderSong)',
    desc: 'Embed a voice command into carrier audio (music, ambient noise). ASR transcribes the hidden command while humans hear only the carrier. Practically dangerous.',
    params: ['carrier_audio', 'asr_model', 'command_text', 'epsilon', 'iterations', 'lr', 'optimizer'],
  },
  muting: {
    id: 'muting',
    name: 'Universal Muting',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: false,
    cat: 'ASR — Universal',
    threat: 'both',
    year: 2024,
    norm: 'L∞',
    authors: 'Vyas et al. (EMNLP)',
    desc: 'Learn a short universal noise segment that, when prepended to ANY audio, makes Whisper output silence or a target phrase. Input-agnostic — one perturbation works on all inputs.',
    params: ['audio', 'asr_model', 'mode', 'segment_duration', 'iterations', 'lr'],
  },
  psycho: {
    id: 'psycho',
    name: 'Psychoacoustic',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Imperceptible',
    threat: 'whitebox',
    year: 2019,
    norm: 'Masking',
    authors: 'Qin et al. (ICML)',
    desc: 'Uses hearing-threshold psychoacoustic masking to hide perturbations below human perception. Truly imperceptible to listeners while fooling ASR. Frequency-domain constrained.',
    params: ['audio', 'asr_model', 'target_text', 'iterations', 'lr', 'masking_weight'],
  },
  ota: {
    id: 'ota',
    name: 'Over-the-Air Robust',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Physical',
    threat: 'both',
    year: 2020,
    norm: 'L∞',
    authors: 'Schönherr et al.',
    desc: 'Perturbations robust to speaker → air → microphone playback. Simulates room impulse responses and background noise during optimisation. Works in physical environments.',
    params: ['audio', 'asr_model', 'target_text', 'epsilon', 'iterations', 'lr', 'n_rooms', 'noise_snr'],
  },
  jamming: {
    id: 'jamming',
    name: 'Speech Jamming',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: false,
    cat: 'ASR — Disruptive',
    threat: 'whitebox',
    year: 2022,
    norm: 'L∞',
    authors: 'Denial-of-Service',
    desc: 'Denial-of-service: degrade ASR accuracy to gibberish. Untargeted (maximise cross-entropy) or band-limited noise constrained to specific frequency ranges.',
    params: ['audio', 'asr_model', 'method', 'epsilon', 'iterations', 'lr', 'band_hz'],
  },
  genetic: {
    id: 'genetic',
    name: 'Genetic (Black-box)',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Black-box',
    threat: 'blackbox',
    year: 2019,
    norm: 'L∞',
    authors: 'Taori et al.',
    desc: 'Decision-based black-box targeted transcription. Phase 1 runs a genetic algorithm (momentum mutation + adaptive rate) to match the target text using only the transcription output; phase 2 uses NES gradient estimation to shrink the perturbation. No model gradients used.',
    params: ['audio', 'asr_model', 'target_text', 'epsilon', 'population_size', 'genetic_iterations', 'gradient_estimation_iterations'],
  },
  siren: {
    id: 'siren',
    name: 'SirenAttack (PSO)',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: false,
    cat: 'ASR — Black-box',
    threat: 'blackbox',
    year: 2020,
    norm: 'L∞',
    authors: 'Du et al. (ASIACCS)',
    desc: 'Gradient-free particle-swarm optimization. A swarm of candidate perturbations converges on an adversarial example using only scalar loss/scores. Supports targeted (force transcript) and untargeted (degrade output) modes.',
    params: ['audio', 'asr_model', 'mode', 'target_text', 'epsilon', 'n_particles', 'iterations'],
  },
  taskcontrol: {
    id: 'taskcontrol',
    name: 'Task-Control (Prompt Injection)',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: false,
    cat: 'ASR — Universal',
    threat: 'both',
    year: 2024,
    norm: 'L∞',
    authors: 'Vyas et al. (EMNLP)',
    desc: 'Universal audio prefix that hijacks Whisper\u2019s multitask control tokens \u2014 forcing it to translate instead of transcribe (or switch language) regardless of the input speech. Acoustic prompt-injection. Requires a multilingual Whisper checkpoint.',
    params: ['audio', 'asr_model', 'task', 'language', 'segment_duration', 'iterations', 'lr'],
  },
  advpulse: {
    id: 'advpulse',
    name: 'AdvPulse',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Physical',
    threat: 'both',
    year: 2020,
    norm: 'L∞',
    authors: 'Li et al. (CCS)',
    desc: 'Subsecond, synchronization-free, universal targeted pulse. A short (~0.1-0.5s) perturbation trained over random injection offsets so it works without alignment to the victim speech. Optional over-the-air robustness (room impulse + noise).',
    params: ['audio', 'asr_model', 'target_text', 'pulse_duration', 'epsilon', 'iterations', 'lr', 'physical'],
  },
  ua3: {
    id: 'ua3',
    name: 'UA3 (Universal Audio Adversarial)',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Multi-Model',
    threat: 'both',
    year: 2025,
    norm: 'L∞',
    authors: 'Maerifat',
    desc: 'One perturbation that fools ALL selected ASR architectures simultaneously (Whisper + Wav2Vec2 + HuBERT). Multi-model ensemble optimisation with augmentation for cross-architecture transfer.',
    params: ['audio', 'model_ensemble', 'target_text', 'iterations', 'epsilon', 'lr'],
  },
  classification: {
    id: 'classification',
    name: 'Audio Classification',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: false,
    requiresTargetText: false,
    cat: 'Audio — Classification',
    threat: 'whitebox',
    year: 2015,
    norm: 'L∞/L2',
    authors: 'Various (FGSM/PGD/C&W/MI-FGSM)',
    desc: 'Standard adversarial attacks adapted for audio classification models (speech commands, emotion, language ID). Choose from 6 attack methods with customisable parameters.',
    params: ['audio', 'audio_model', 'target_label', 'attack_method', 'epsilon', 'iterations'],
  },
}
