export const THREAT_COLORS = {
  whitebox: 'text-cyan-400 bg-cyan-400/10 border-cyan-400/30',
  blackbox: 'text-orange-400 bg-orange-400/10 border-orange-400/30',
  both: 'text-purple-400 bg-purple-400/10 border-purple-400/30',
}

export const THREAT_LABEL = {
  whitebox: 'White-box',
  blackbox: 'Black-box',
  both: 'WB + BB',
}

export const AUDIO_ATTACK_REGISTRY = {
  transcription: {
    id: 'transcription',
    name: 'Targeted Transcription',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Targeted',
    threat: 'whitebox',
    year: 2018,
    norm: 'L∞',
    authors: 'Carlini & Wagner',
    desc: 'Force ASR to output an attacker-chosen transcript. C&W optimisation (Adam) or PGD sign-based. Modifies audio so Whisper outputs exact target text.',
    params: ['audio', 'asr_model', 'target_text', 'epsilon', 'iterations', 'lr', 'optimizer'],
  },
  hidden: {
    id: 'hidden',
    name: 'Hidden Command',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Targeted',
    threat: 'whitebox',
    year: 2018,
    norm: 'L∞',
    authors: 'Yuan et al. (CommanderSong)',
    desc: 'Embed a voice command into carrier audio (music, ambient noise). ASR transcribes the hidden command while humans hear only the carrier. Practically dangerous.',
    params: ['carrier_audio', 'asr_model', 'command_text', 'epsilon', 'iterations', 'lr', 'optimizer'],
  },
  muting: {
    id: 'muting',
    name: 'Universal Muting',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: false,
    cat: 'ASR — Universal',
    threat: 'both',
    year: 2024,
    norm: 'L∞',
    authors: 'Vyas et al. (EMNLP)',
    desc: 'Learn a short universal noise segment that, when prepended to ANY audio, makes Whisper output silence or a target phrase. Input-agnostic — one perturbation works on all inputs.',
    params: ['audio', 'asr_model', 'mode', 'segment_duration', 'iterations', 'lr'],
  },
  psycho: {
    id: 'psycho',
    name: 'Psychoacoustic',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Imperceptible',
    threat: 'whitebox',
    year: 2019,
    norm: 'Masking',
    authors: 'Qin et al. (ICML)',
    desc: 'Uses hearing-threshold psychoacoustic masking to hide perturbations below human perception. Truly imperceptible to listeners while fooling ASR. Frequency-domain constrained.',
    params: ['audio', 'asr_model', 'target_text', 'iterations', 'lr', 'masking_weight'],
  },
  ota: {
    id: 'ota',
    name: 'Over-the-Air Robust',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Physical',
    threat: 'both',
    year: 2020,
    norm: 'L∞',
    authors: 'Schönherr et al.',
    desc: 'Perturbations robust to speaker → air → microphone playback. Simulates room impulse responses and background noise during optimisation. Works in physical environments.',
    params: ['audio', 'asr_model', 'target_text', 'epsilon', 'iterations', 'lr', 'n_rooms', 'noise_snr'],
  },
  jamming: {
    id: 'jamming',
    name: 'Speech Jamming',
    robustnessSupported: true,
    benchmarkSupported: true,
    transferSupported: true,
    requiresTargetText: false,
    cat: 'ASR — Disruptive',
    threat: 'whitebox',
    year: 2022,
    norm: 'L∞',
    authors: 'Denial-of-Service',
    desc: 'Denial-of-service: degrade ASR accuracy to gibberish. Untargeted (maximise cross-entropy) or band-limited noise constrained to specific frequency ranges.',
    params: ['audio', 'asr_model', 'method', 'epsilon', 'iterations', 'lr', 'band_hz'],
  },
  ua3: {
    id: 'ua3',
    name: 'UA3 (Universal Audio Adversarial)',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: true,
    requiresTargetText: true,
    cat: 'ASR — Multi-Model',
    threat: 'both',
    year: 2025,
    norm: 'L∞',
    authors: 'Maerifat',
    desc: 'One perturbation that fools ALL selected ASR architectures simultaneously (Whisper + Wav2Vec2 + HuBERT). Multi-model ensemble optimisation with augmentation for cross-architecture transfer.',
    params: ['audio', 'model_ensemble', 'target_text', 'iterations', 'epsilon', 'lr'],
  },
  classification: {
    id: 'classification',
    name: 'Audio Classification',
    robustnessSupported: false,
    benchmarkSupported: false,
    transferSupported: false,
    requiresTargetText: false,
    cat: 'Audio — Classification',
    threat: 'whitebox',
    year: 2015,
    norm: 'L∞/L2',
    authors: 'Various (FGSM/PGD/C&W/MI-FGSM)',
    desc: 'Standard adversarial attacks adapted for audio classification models (speech commands, emotion, language ID). Choose from 6 attack methods with customisable parameters.',
    params: ['audio', 'audio_model', 'target_label', 'attack_method', 'epsilon', 'iterations'],
  },
}
