export const THREAT_COLORS = {
  whitebox: 'text-cyan-400 bg-cyan-400/10 border-cyan-400/30',
  blackbox: 'text-orange-400 bg-orange-400/10 border-orange-400/30',
  both: 'text-purple-400 bg-purple-400/10 border-purple-400/30',
}

export const THREAT_LABEL = {
  whitebox: 'White-box',
  blackbox: 'Black-box',
  both: 'WB + BB',
}

export const SARABCRAFT_R1_NAME = 'SarabCraft R1'

export const FALLBACK_REGISTRY = {
  "FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2015, norm:"L∞", authors:"Goodfellow et al.", desc:"Single-step gradient sign perturbation. Fastest but weakest attack.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16} } },
  "I-FGSM (BIM)": { cat:"Gradient (L∞)", threat:"whitebox", year:2017, norm:"L∞", authors:"Kurakin et al.", desc:"Iterative FGSM with small steps. Stronger than single-step FGSM.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:40}, alpha:{label:"Step multiplier (α)",min:0.1,max:10,step:0.1,default:1.0} } },
  "PGD": { cat:"Gradient (L∞)", threat:"whitebox", year:2018, norm:"L∞", authors:"Madry et al.", desc:"Projected Gradient Descent with random start. Standard strong white-box baseline.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:50}, alpha:{label:"Step multiplier (α)",min:0.1,max:10,step:0.1,default:1.0}, random_start:{label:"Random start",type:"bool",default:true} } },
  "APGD": { cat:"Gradient (L∞)", threat:"whitebox", year:2020, norm:"L∞/L2", authors:"Croce & Hein", desc:"Auto-PGD: adaptive step-size schedule + DLR loss. Parameter-free, strictly stronger than PGD.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:2000,step:10,default:100}, apgd_loss:{label:"Loss function",type:"select",options:["dlr","ce"],default:"dlr"}, n_restarts:{label:"Restarts",min:1,max:10,step:1,default:1}, rho:{label:"Step decay (ρ)",min:0.1,max:1,step:0.05,default:0.75} } },
  "MI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2018, norm:"L∞", authors:"Dong et al.", desc:"Momentum Iterative FGSM. Accumulates gradient momentum for better transferability.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, alpha:{label:"Step multiplier (α)",min:0.1,max:10,step:0.1,default:1.0}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0} } },
  "DI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2019, norm:"L∞", authors:"Xie et al.", desc:"Diverse Input FGSM. Random resize-pad transform at each step improves transfer.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, p_di:{label:"DI probability",min:0.1,max:1,step:0.1,default:0.7} } },
  "TI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2019, norm:"L∞", authors:"Dong et al.", desc:"Translation-Invariant FGSM. Gaussian kernel smooths gradients for shift invariance.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, kernel_size:{label:"TI kernel size",min:3,max:15,step:2,default:5} } },
  "NI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2020, norm:"L∞", authors:"Lin et al.", desc:"Nesterov Iterative FGSM. Computes gradient at lookahead position for faster convergence.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0} } },
  "SI-NI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2020, norm:"L∞", authors:"Lin et al.", desc:"Scale-Invariant Nesterov FGSM. Averages gradients at multiple image scales.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, n_scale:{label:"# Scales",min:2,max:10,step:1,default:5} } },
  "VMI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2021, norm:"L∞", authors:"Wang & He", desc:"Variance-Tuned MI-FGSM. Adds neighbourhood gradient variance to reduce overfitting.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, n_var:{label:"Variance samples",min:5,max:30,step:5,default:20}, beta_var:{label:"Variance scale (β)",min:0.5,max:5,step:0.1,default:1.5} } },
  "VNI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2021, norm:"L∞", authors:"Wang & He", desc:"Variance-tuned Nesterov FGSM. Combines VMI variance with Nesterov lookahead momentum.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, n_var:{label:"Variance samples",min:5,max:30,step:5,default:20}, beta_var:{label:"Variance scale (β)",min:0.5,max:5,step:0.1,default:1.5} } },
  "PI-FGSM": { cat:"Gradient (L∞)", threat:"whitebox", year:2020, norm:"L∞", authors:"Gao et al.", desc:"Patch-wise Iterative FGSM. Amplifies perturbation through project kernel for targeted transfer.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:500,step:1,default:10}, amplification:{label:"Amplification",min:1,max:50,step:1,default:10}, pi_prob:{label:"DI probability",min:0.1,max:1,step:0.1,default:0.7}, pi_kern_size:{label:"Kernel size",min:3,max:15,step:2,default:3} } },
  "Jitter": { cat:"Gradient (L∞)", threat:"whitebox", year:2021, norm:"L∞", authors:"Schwinn et al.", desc:"PGD with random neighbourhood sampling before each gradient step. Escapes sharp local minima.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:2000,step:1,default:50}, alpha:{label:"Step multiplier (α)",min:0.1,max:10,step:0.1,default:1.0}, random_start:{label:"Random start",type:"bool",default:true}, jitter_ratio:{label:"Jitter ratio",min:0.01,max:0.5,step:0.01,default:0.1} } },
  "DeepFool": { cat:"Optimization (L2)", threat:"whitebox", year:2016, norm:"L2", authors:"Moosavi-Dezfooli et al.", desc:"Finds minimal perturbation to cross the decision boundary. Iterative linearisation.", params:{ epsilon:{label:"Max epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:500,step:10,default:100}, overshoot:{label:"Overshoot",min:0.01,max:0.5,step:0.01,default:0.02} } },
  "C&W (L2)": { cat:"Optimization (L2)", threat:"whitebox", year:2017, norm:"L2", authors:"Carlini & Wagner", desc:"Optimization-based L2 attack using Adam. Highly effective, slower. Gold standard for L2.", params:{ epsilon:{label:"Max epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:100,max:5000,step:100,default:1000}, cw_confidence:{label:"Confidence (κ)",min:0,max:50,step:1,default:0}, cw_lr:{label:"Learning rate",min:0.001,max:0.1,step:0.001,default:0.01}, cw_c:{label:"Constant (c)",min:0.1,max:100,step:0.1,default:1.0} } },
  "FAB": { cat:"Optimization (L2)", threat:"whitebox", year:2020, norm:"L∞/L2/L1", authors:"Croce & Hein", desc:"Fast Adaptive Boundary: finds closest adversarial by projecting onto decision boundary.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:500,step:10,default:100}, fab_alpha_max:{label:"Max step (α_max)",min:0.01,max:1,step:0.01,default:0.1}, fab_eta:{label:"Overshoot (η)",min:1.0,max:2.0,step:0.05,default:1.05}, fab_beta:{label:"Backward step (β)",min:0.1,max:1,step:0.1,default:0.9}, n_restarts:{label:"Restarts",min:1,max:10,step:1,default:1} } },
  "JSMA": { cat:"Sparse (L0)", threat:"whitebox", year:2016, norm:"L0", authors:"Papernot et al.", desc:"Jacobian Saliency Map Attack. Uses Jacobian to find most impactful pixels. Changes fewest pixels.", params:{ theta:{label:"Perturbation step (θ)",min:-1,max:1,step:0.1,default:1.0}, gamma:{label:"Max pixel fraction (γ)",min:0.01,max:0.5,step:0.01,default:0.1} } },
  "EAD (Elastic Net)": { cat:"Sparse (L1)", threat:"whitebox", year:2018, norm:"L1+L2", authors:"Chen et al.", desc:"Elastic-Net Attack: L1+L2 regularised C&W variant. Produces sparse perturbations via ISTA.", params:{ epsilon:{label:"Max epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:50,max:2000,step:50,default:200}, cw_lr:{label:"Learning rate",min:0.001,max:0.1,step:0.001,default:0.01}, cw_c:{label:"Constant (c)",min:0.1,max:100,step:0.1,default:1.0}, cw_confidence:{label:"Confidence (κ)",min:0,max:50,step:1,default:0}, ead_beta:{label:"L1 weight (β)",min:0.0001,max:0.1,step:0.0001,default:0.001}, ead_rule:{label:"Decision rule",type:"select",options:["EN","L1"],default:"EN"} } },
  "SparseFool": { cat:"Sparse (L1)", threat:"whitebox", year:2019, norm:"L1", authors:"Modas et al.", desc:"Sparse DeepFool: finds minimal L1 perturbation by keeping only most salient pixel changes.", params:{ epsilon:{label:"Max epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:500,step:10,default:100}, overshoot:{label:"Overshoot",min:0.01,max:0.5,step:0.01,default:0.02}, sf_lambda:{label:"Sparsity (λ)",min:0.1,max:10,step:0.1,default:1.0} } },
  "SSA": { cat:"Transfer", threat:"both", year:2022, norm:"L∞", authors:"Long et al.", desc:"Spectrum Simulation Attack: augments in DCT frequency domain to prevent model-specific overfitting.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:500,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, n_spectrum:{label:"Spectrum samples",min:5,max:50,step:5,default:20}, rho_spectrum:{label:"Keep ratio (ρ)",min:0.1,max:1,step:0.1,default:0.5} } },
  "Admix": { cat:"Transfer", threat:"both", year:2021, norm:"L∞", authors:"Wang et al.", desc:"Admix: mixes random images into input during attack to prevent overfitting to source model.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:500,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, n_mix:{label:"Mix copies",min:1,max:10,step:1,default:5}, mix_ratio:{label:"Mix ratio (η)",min:0.05,max:0.5,step:0.05,default:0.2} } },
  "BSR": { cat:"Transfer", threat:"both", year:2024, norm:"L∞", authors:"Wang et al.", desc:"Block Shuffle & Rotation: randomly shuffles and rotates image blocks for transfer robustness.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:1,max:500,step:1,default:20}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, n_block:{label:"Blocks per axis",min:2,max:8,step:1,default:3}, rotation_range:{label:"Rotation (°)",min:0,max:45,step:5,default:10} } },
  "Square Attack": { cat:"Black-Box", threat:"blackbox", year:2020, norm:"L∞/L2", authors:"Andriushchenko et al.", desc:"Score-based random search with square-shaped colour patches. NO gradients needed. Query-efficient.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, n_queries:{label:"Max queries",min:100,max:50000,step:100,default:5000}, p_init:{label:"Initial square size",min:0.1,max:1,step:0.1,default:0.8} } },
  "SPSA": { cat:"Black-Box", threat:"blackbox", year:2018, norm:"L∞", authors:"Uesato et al.", desc:"Estimates gradients via random perturbation pairs. Works with only model output probabilities.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:1000,step:10,default:100}, spsa_delta:{label:"Estimation delta (δ)",min:0.001,max:0.1,step:0.001,default:0.01}, spsa_lr:{label:"Learning rate",min:0.001,max:0.1,step:0.001,default:0.01}, nb_sample:{label:"Samples per step",min:16,max:512,step:16,default:128} } },
  "One Pixel": { cat:"Black-Box", threat:"blackbox", year:2019, norm:"L0", authors:"Su, Vargas & Kouichi", desc:"Differential evolution to find best 1-10 pixels to change. Famous L0 attack. No gradients.", params:{ pixels:{label:"Pixels to change",min:1,max:10,step:1,default:5}, popsize:{label:"Population size",min:50,max:1000,step:50,default:400}, iterations:{label:"Generations",min:10,max:300,step:10,default:75} } },
  "Boundary Attack": { cat:"Black-Box", threat:"blackbox", year:2018, norm:"L2", authors:"Brendel et al.", desc:"Decision-based: starts from adversarial noise, walks along boundary toward clean image. Hard-label only.", params:{ epsilon:{label:"Max epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Steps",min:100,max:20000,step:100,default:5000}, boundary_delta:{label:"Orthogonal step (δ)",min:0.001,max:0.1,step:0.001,default:0.01}, boundary_step:{label:"Toward-original step",min:0.001,max:0.1,step:0.001,default:0.01} } },
  "HopSkipJump": { cat:"Black-Box", threat:"blackbox", year:2020, norm:"L2", authors:"Chen et al.", desc:"Improved boundary attack with gradient estimation via binary search + Monte Carlo sampling.", params:{ epsilon:{label:"Max epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Steps",min:10,max:500,step:10,default:50}, hsj_init_evals:{label:"Initial eval samples",min:50,max:500,step:50,default:100}, hsj_max_evals:{label:"Max eval samples",min:100,max:5000,step:100,default:1000}, hsj_gamma:{label:"Step scale (γ)",min:0.1,max:5,step:0.1,default:1.0} } },
  "Adversarial Patch": { cat:"Physical", threat:"both", year:2017, norm:"Patch", authors:"Brown et al.", desc:"Optimises a small patch that causes misclassification when placed on any image. Works physically.", params:{ iterations:{label:"Iterations",min:50,max:2000,step:50,default:500}, patch_lr:{label:"Learning rate",min:0.001,max:0.1,step:0.001,default:0.01}, patch_ratio:{label:"Patch size (fraction)",min:0.05,max:0.5,step:0.05,default:0.1} } },
  "UAP": { cat:"Physical", threat:"whitebox", year:2017, norm:"L2", authors:"Moosavi-Dezfooli et al.", desc:"Universal Adversarial Perturbation: single image-agnostic noise that fools the model on most inputs.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:500,step:10,default:100}, overshoot:{label:"Overshoot",min:0.01,max:0.5,step:0.01,default:0.02} } },
  "AutoAttack": { cat:"Meta", threat:"both", year:2020, norm:"L∞/L2", authors:"Croce & Hein", desc:"THE gold standard. Ensemble of APGD-CE, APGD-DLR, FAB, Square Attack. Parameter-free robustness eval.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Budget per sub-attack",min:20,max:500,step:10,default:100}, aa_version:{label:"Version",type:"select",options:["standard","fast"],default:"standard"} } },
  [SARABCRAFT_R1_NAME]: { cat:"Research", threat:"both", year:2026, norm:"L∞", authors:"SarabCraft Research", desc:"SarabCraft's first in-house transfer-focused image attack. Standard mode prioritizes strong single-model transfer, while multi-image transfer mode unlocks broader bank-building strategies for harder evaluations.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:50,max:2000,step:50,default:300}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, kernel_size:{label:"TI kernel size",min:3,max:15,step:2,default:5}, cfm_mix_prob:{label:"CFM mix probability",min:0,max:0.5,step:0.01,default:0.1}, cfm_mix_upper:{label:"CFM mix upper bound",min:0.1,max:1,step:0.05,default:0.75}, r1_multi_image_strategy:{label:"Multi-image strategy",type:"select",options:["tile_shuffle","progressive","self_aug_bank","self_mix"],default:"tile_shuffle",hiddenInInfo:true}, r1_multi_image_count:{label:"Image count",min:2,max:30,step:1,default:10,hiddenInInfo:true} } },
  "CFM Paper (CVPR 2023)": { cat:"Transfer", threat:"both", year:2023, norm:"L∞", authors:"Byun et al.", desc:"Exact Config 578 from the CFM paper: CFM + RDI + MI + TI + Logit Loss. Strongest single-model transfer baseline prior to PHANTOM. Uses Resized Diverse Input (RDI) augmentation.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:50,max:2000,step:50,default:300}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, kernel_size:{label:"TI kernel size",min:3,max:15,step:2,default:5}, cfm_mix_prob:{label:"CFM mix prob",min:0,max:0.5,step:0.01,default:0.1}, cfm_mix_upper:{label:"CFM mix upper",min:0.1,max:1,step:0.05,default:0.75} } },
  "NewBackend (TA-Bench)": { cat:"Transfer", threat:"both", year:2023, norm:"L∞", authors:"Qin et al. (NeurIPS 2023)", desc:"UN+PI+DI+TI+NI+MI — strongest composite baseline from the Transfer-Attack Benchmark. Six combined techniques for maximum transfer.", params:{ epsilon:{label:"Epsilon (/255)",min:1,max:100,step:1,default:16}, iterations:{label:"Iterations",min:10,max:2000,step:10,default:300}, momentum_decay:{label:"Momentum (μ)",min:0,max:1,step:0.1,default:1.0}, nb_di_prob:{label:"DI probability",min:0.1,max:1,step:0.1,default:0.5}, nb_di_resize_rate:{label:"DI resize rate",min:0.5,max:1,step:0.05,default:0.9}, nb_ti_len:{label:"TI translation (px)",min:0,max:15,step:1,default:3}, nb_npatch:{label:"PI # patches",min:16,max:256,step:16,default:128}, nb_grid_scale:{label:"PI grid scale",min:4,max:32,step:4,default:16}, nb_enable_un:{label:"Uniform Noise (UN)",type:"bool",default:true}, nb_enable_pi:{label:"Patch Interaction (PI)",type:"bool",default:true}, nb_enable_di:{label:"Diverse Input (DI)",type:"bool",default:true}, nb_enable_ti:{label:"Translation Inv. (TI)",type:"bool",default:true}, nb_enable_ni:{label:"Nesterov (NI)",type:"bool",default:true} } },
}
